### ISSUE TITLE
Das Skript kann nicht ausgeführt werden

### ISSUE THREAD

**Issue by Fendmann** [github-gabriel/navigium-solver#1]
Hallo

Leider kann das Skript bei mir nicht ausgeführt werden. 
Und ja, ich habe den Chrome Driver installiert.

**Comment by github-gabriel** [comment]
Hallo,

ja das ist merkwürdig. Kriegst du denn eine Fehlermeldung oder schließt sich das Terminal einfach? Außerdem ist wichtig, darauf zu achten, dass der Treiber dieselbe Version hat, wie dein Chromium basierter Browser (Bei Chrome einfach oben rechts auf die drei Punkte > Hilfe > Über Google Chrome).

**Comment by Fendmann** [comment]
Hallo

Wenn ich das Skript ausführe, schleißt sich das terminal gleich wieder. 
Der Treiber hat dieselbe version wie mein Browser

**Comment by github-gabriel** [comment]
Besteht das Problem noch weiter, oder konnten die anderen geöffneten Issues helfen? (https://github.com/github-gabriel/navigium-solver/issues/2, https://github.com/github-gabriel/navigium-solver/issues/3) Sonst würde ich das Issue hier auch schließen, falls es keine weiteren Probleme/Rückfragen gibt

**Comment by github-gabriel** [comment]
Schließen wegen wenig Aktivität. Bei weiteren Fragen/Problem gerne ein neues Issue öffnen
