### ISSUE TITLE
Das Program startet bei mir ebenfalls nicht.

### ISSUE THREAD

**Issue by bubatzschmuggler** [github-gabriel/navigium-solver#2]

**Comment by bubatzschmuggler** [comment]
Oh! Das habe ich noch nicht getan, danke für die Hilfe.

**Comment by github-gabriel** [comment]
Jo kein Problem. Ich habe auch vergessen das in der README zu erwähnen, aber genau, das Script übernimmt das Einloggen für dich in der "login" Methode.
